name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Release_AVX, Release_AVX2, Release_G1_AVX, Release_G1_AVX2, Release, Release_G1, Spacer_NET, Launcher ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build configuration
        uses: ./.github/actions/build
        with:
          configuration: ${{ matrix.configuration }}

  package-nightly-artifacts:
    if: github.ref_name == 'master'
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Package artifacts
        uses: ./.github/actions/package-artifacts
        with:
          nightly: true
          artifact-name: "deployment-files"
          include-spacer-net: false

  deploy-nightly-release:
    if: github.ref_name == 'master'
    needs: package-artifacts
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create nightly release
        uses: ./.github/actions/deploy-artifacts
        with:
          nightly: true
          artifact-name: "deployment-files"
          token: ${{ secrets.GITHUB_TOKEN }}
