name: Build and conditional release

on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

  workflow_dispatch:

env:
  IS_RELEASE_TRIGGER: ${{ github.event_name == 'push' && (github.ref_name == 'master' || github.ref_type == 'tag') }}
  IS_NIGHTLY_RELEASE: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

jobs:
  build:
    name: build (${{ matrix.configuration }})
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - configuration: Launcher
            project: Launcher/Launcher.vcxproj
            output-file: ddraw.dll

          - configuration: Release
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g2a.dll

          - configuration: Release_AVX
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g2a_avx.dll

          - configuration: Release_AVX2
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g2a_avx2.dll

          - configuration: Release_G1
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g1.dll

          - configuration: Release_G1_12f
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g1a.dll

          - configuration: Release_G1_AVX
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g1_avx.dll

          - configuration: Release_G1_AVX2
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g1_avx2.dll

          - configuration: Spacer_NET
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g2_spacer.dll

          - configuration: Spacer_NET_G1
            project: D3D11Engine/D3D11Engine.vcxproj
            output-file: g1_spacer.dll

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build configuration
        uses: ./.github/actions/build-configuration
        with:
          configuration: ${{ matrix.configuration }}
          project: ${{ matrix.project }}
          output-file: ${{ matrix.output-file }}

  package-artifacts:
    needs: build
    runs-on: ubuntu-latest

    outputs:
      artifact-id: ${{ steps.package-artifacts.outputs.artifact-id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Package artifacts
        id: package-artifacts
        uses: ./.github/actions/package-artifacts

  create-release:
    if: env.IS_RELEASE_TRIGGER == 'true'
    needs: package-artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout only composite actions
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/actions
          filter: blob:none

      - name: Create nightly release
        uses: ./.github/actions/deploy-artifacts
        with:
          nightly: ${{ env.IS_NIGHTLY_RELEASE }}
          artifact-id: ${{ needs.package-artifacts.outputs.artifact-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
