name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

  workflow_dispatch:

jobs:
  build:
    name: build (${{ matrix.configuration }})
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - configuration: Launcher
            project: Launcher/Launcher.vcxproj
            output: ddraw.dll

          - configuration: Release
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g2a.dll

          - configuration: Release_AVX
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g2a_avx.dll

          - configuration: Release_AVX2
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g2a_avx2.dll

          - configuration: Release_G1
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g1.dll

          - configuration: Release_G1_12f
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g1a.dll

          - configuration: Release_G1_AVX
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g1_avx.dll

          - configuration: Release_G1_AVX2
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g1_avx2.dll

          - configuration: Spacer_NET
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g2_spacer.dll

          - configuration: Spacer_NET_G1
            project: D3D11Engine/D3D11Engine.vcxproj
            output: g1_spacer.dll

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build configuration
        uses: ./.github/actions/build-configuration
        with:
          configuration: ${{ matrix.configuration }}
          project: ${{ matrix.project }}
          output: ${{ matrix.output }}

  package-nightly-artifacts:
    #if: github.ref_name == 'master'
    needs: build
    runs-on: windows-latest

    outputs:
      artifact-id: ${{ steps.package-artifacts.outputs.artifact-id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Package artifacts
        id: package-artifacts
        uses: ./.github/actions/package-artifacts
        with:
          nightly: true

  deploy-nightly-release:
    #if: github.ref_name == 'master'
    needs: package-nightly-artifacts
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create nightly release
        uses: ./.github/actions/deploy-artifacts
        with:
          nightly: true
          artifact-id: ${{ needs.package-nightly-artifacts.outputs.artifact-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
