name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Release_AVX, Release_AVX2, Release_G1_AVX, Release_G1_AVX2, Release, Release_G1, Spacer_NET, Launcher ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build target
        uses: ./.github/actions/build-target
        with:
          target: ${{ matrix.configuration }}

  deploy-release:
    # if: github.ref_name == 'master'
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup env vars
        uses: ./.github/actions/setup-env-vars
        with:
          nightly: true

      - name: Package nightly artifact
        uses: ./.github/actions/package-artifact
        with:
          include-spacer-net: false

      - name: Create nightly release
        uses: ./.github/actions/deploy-artifact
        with:
          nightly: true
