name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Release_AVX, Release_AVX2, Release_G1_AVX, Release_G1_AVX2, Release, Release_G1, Spacer_NET, Launcher ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build configuration
        uses: ./.github/actions/build
        with:
          configuration: ${{ matrix.configuration }}

  package-artifacts:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Package artifacts
        uses: ./.github/actions/package-artifacts
        with:
          nightly: false
          artifact-name: "deployment-files"
          include-spacer-net: true

  deploy-release:
    needs: package-artifacts
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create release
        uses: ./.github/actions/deploy-artifacts
        with:
          nightly: false
          artifact-name: "deployment-files"
          token: ${{ secrets.GITHUB_TOKEN }}
