name: Release

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Release_AVX, Release_AVX2, Release_G1_AVX, Release_G1_AVX2, Release, Release_G1, Spacer_NET, Launcher ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build configuration
        uses: ./.github/actions/build
        with:
          configuration: ${{ matrix.configuration }}

  deploy-release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Calculate path names
        uses: ./.github/actions/calc_path_names
        with:
          nightly: false

      - name: Package artifacts
        uses: ./.github/actions/package-artifacts
        with:
          include-spacer-net: true
          release_dir: $RELEASE_DIR
          spacer_release_dir: $SPACER_RELEASE_DIR

      - name: Create release
        uses: ./.github/actions/deploy-artifacts
        with:
          nightly: false
          release_dir: $RELEASE_DIR
          spacer_release_dir: $SPACER_RELEASE_DIR
          token: ${{ secrets.GITHUB_TOKEN }}
